### ISSUE TITLE
class syntax in all red

### ISSUE THREAD

**Issue by tylerthehaas** [mhartington/vscode-oceanicnext#1]
The class syntax showing all red. The top line has proper colloring and method definitions are fine but everything else shows red.  below is a screenshot of the issue.

![screen shot 2016-02-23 at 4 58 32 pm](https://cloud.githubusercontent.com/assets/11150235/13270952/bdcf1cb4-da4e-11e5-98b9-0a0e3e3a097b.png)

**Comment by mhartington** [comment]
Closing as this does not appear to be valid any more
