### ISSUE TITLE
Titlte Bar Color

### ISSUE THREAD

**Issue by haveanicedavid** [mhartington/vscode-oceanicnext#4]
VSCode added the ability to customize the title bar color a few releases ago. 

Would it be possible to include that in this theme?

![screenshot 2018-03-28 14 51 21](https://user-images.githubusercontent.com/9052511/38055711-befe22f8-3297-11e8-9394-53f9b0dd2e71.png)

Versus: 

![screenshot 2018-03-28 14 53 55](https://user-images.githubusercontent.com/9052511/38055765-e025993e-3297-11e8-86c0-0cac8dfe2b95.png)

**Comment by fwojciec** [comment]
I've created a PR changing the inactive bg color of the titleBar to be the same as the active color -- for more consistent look.
https://github.com/mhartington/vscode-oceanicnext/pull/7

**Comment by mhartington** [comment]
Just merged. Will release and update
